stages:
  - build
  - test
  - quality
  - analysis
  - package

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

#default:
#  before_script:
#    - chmod +x mvnw

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: 0


build_job:
  stage: build
  image: registry.access.redhat.com/openjdk/openjdk-11-rhel7:1.0-13
  allow_failure: false
  script:
    - ./mvnw compile
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true


test_job:
  stage: test
  image: registry.access.redhat.com/openjdk/openjdk-11-rhel7:1.0-13
  services:
    - docker:stable-dind
  script:
    - ./mvnw jacoco:prepare-agent test
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true


code_quality_job:
  stage: quality
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - mkdir codequality-results
    - docker run
        --env CODECLIMATE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        --volume /tmp/cc:/tmp/cc
        codeclimate/codeclimate analyze -f html > ./codequality-results/index.html
  artifacts:
    paths:
      - codequality-results/
  only:
    - merge_requests
    - master
    - develop

sonar_job:
  stage: sonar
  image: registry.access.redhat.com/openjdk/openjdk-11-rhel7:1.0-13
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - ./mvnw test sonar:sonar
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      -Dsonar.qualitygate.wait=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
      -P gitlab
  only:
    - merge_requests
    - master
    - develop


sonar_job:
  stage: analysis
  image: adoptopenjdk/openjdk11:alpine-slim
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    SONAR_TOKEN: "d8363e498a11c57a4a5402e11c42dcab669c767b"
    SONAR_HOST_URL: "https://sonarcloud.io/dashboard?id=com.tdevilleduc.urthehero%3Aurthehero"
    GIT_DEPTH: 0
  script:
    - ./mvnw jacoco:prepare-agent install
    - ./mvnw verify sonar:sonar
  only:
    - merge_requests
    - master
    - develop


package_job:
  stage: package
  image: docker:stable
  allow_failure: false
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./mvnw install dockerfile:build dockerfile:push -DskipTests=true
      -Ddocker.registry=$CI_REGISTRY_IMAGE
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  only:
    - master
    - develop
