version: '3.7'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: urthehero-back
    ports:
      - 8083:8083
    networks:
      - network1
 
networks:
  network1: