version: '3.7'

services:
  mysql:
    container_name: urthehero-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: tdevilleduc
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - urthehero

  back:
    container_name: urthehero-back
    image: registry.access.redhat.com/openjdk/openjdk-11-rhel7:1.0-13
#    image: openjdk:14-jdk-alpine
    volumes:
      - ./back/target:/deployments
    #command: "java -jar /deployments/back-0.1.0.jar"
    environment:
      JAVA_APP_JAR: back-0.1.0.jar
    ports:
      - "8083:8083"
    restart: always
    networks:
      - urthehero
    depends_on:
      - mysql

networks:
  urthehero:
    driver: bridge
    name: urthehero
