services:
  postgres:
    container_name: urthehero-postgres
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - urthehero

  back:
    container_name: urthehero-back
    image: eclipse-temurin:21-jre-jammy
    volumes:
      - ./back/target:/deployments
    command: ["java", "-Dspring.profiles.active=docker", "-Dfile.encoding=UTF8", "-jar", "/deployments/back-0.3.0.jar"]
    ports:
      - "8080:8080"
    restart: always
    networks:
      - urthehero
    depends_on:
      - postgres

networks:
  urthehero:
    driver: bridge
    name: urthehero

volumes:
  postgres: