version: '3.7'

services:
  mysql:
    container_name: urthehero-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: tdevilleduc
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - urthehero

  back:
    container_name: urthehero-back
    image: urthehero_back:0.1.0
    volumes:
      - ./back/target:/deployments
    ports:
      - "8083:8083"
    restart: always
    networks:
      - urthehero
    depends_on:
      - mysql

networks:
  urthehero:
    driver: bridge
    name: urthehero
