version: '3.7'

services:
  postgres:
    container_name: urthehero-postgres
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - urthehero

  back:
    container_name: urthehero-back
    image: registry.access.redhat.com/openjdk/openjdk-11-rhel7:1.0-13
    volumes:
      - ./back/target:/deployments
    environment:
      JAVA_APP_JAR: back-0.1.1-SNAPSHOT.jar
      JAVA_OPTIONS: "-Dspring.profiles.active=docker -Dfile.encoding=UTF8"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - urthehero
    depends_on:
      - postgres

networks:
  urthehero:
    driver: bridge
    name: urthehero

volumes:
  postgres: