server:
  port: 8080

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  main:
    banner-mode: "off"
  profiles:
    active: chaos-monkey
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: testuser
    password: test123
    driver-class-name: org.postgresql.Driver
    tomcat:
      validationQuery: SELECT 1
    connection-properties: useUnicode=true;characterEncoding=utf-8;
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

# Actuator
management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    info:
      enabled: true

# Swagger
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
  packagesToScan: com.tdevilleduc.urthehero.back.controller
  pathsToMatch: /authenticate/**, /api/dice/**, /api/page/**, /api/user/**, /api/story/**, /api/progression/**, /api/enemy/**
  api-docs:
    resolve-schema-properties: true

# Resilience4J
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: false
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions: java.lang.Exception
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        recordExceptions: java.lang.Exception
